paths:
  static: public
  uploads: public/uploads

collections_config:
  posts:
    path: src/content/posts
    name: Posts
    icon: newspaper
    _enabled_editors:
      - content
  pages:
    path: src/content/pages
    name: Pages
    icon: laptop
    _enabled_editors:
      - visual

timezone: Pacific/Auckland

markdown:
  engine: commonmark
  options:
    gfm: true
