paths:
  static: public
  uploads: public/images
  data: data

collections_config:
  posts:
    path: src/content/posts
    name: Posts
    icon: newspaper
    _enabled_editors:
      - content
    schemas:
      default:
        name: New Page
        path: schemas/post.md
        remove_extra_inputs: false
  pages:
    path: src/content/pages
    name: Pages
    icon: laptop
    _enabled_editors:
      - visual
    schemas:
      default:
        name: New Page
        path: schemas/page.md
        remove_extra_inputs: false
  data:
    path: data
    name: Data
    icon: analytics

timezone: Pacific/Auckland

markdown:
  engine: commonmark
  options:
    gfm: true

data_config:
  colors:
    path: data/colors.json

file_config:
  - glob: data/colors.json
    _structures:
      color:
        values:
          - value:
              name:
              value:
            preview:
              icon: palette
    _inputs:
      $:
        type: array
        label: Colors
        comment: Set the colors available in the color selectors throughout the site.
        options:
          structures: _structures.color
      value:
        type: color
      name:
        type: text
        comment: What is seen in the color selector dropdown.

_inputs:
  background_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
