paths:
  static: public
  uploads: public/images
  data: data

collections_config:
  posts:
    path: src/content/posts
    name: Posts
    icon: newspaper
    _enabled_editors:
      - content
  pages:
    path: src/content/pages
    name: Pages
    icon: laptop
    _enabled_editors:
      - visual
  data:
    path: data
    name: Data
    icon: analytics

timezone: Pacific/Auckland

markdown:
  engine: commonmark
  options:
    gfm: true

data_config:
  colors:
    path: data/colors.json

_inputs:
  background_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
