paths:
  static: public
  uploads: public/uploads

collections_config:
  posts:
    path: src/content/posts
    name: Posts
    icon: newspaper
  pages:
    path: src/content/pages
    name: Pages
    icon: laptop

timezone: Pacific/Auckland

markdown:
  engine: commonmark
  options:
    gfm: true
